version: '3.8'
services:
  webfluxblog-authentication-server-service: # The name of the service
    container_name: webfluxblog-authentication-server-service  # Setting the container name
    image: webfluxblog-authentication-server-service-local-image
    restart: always # Always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8115:8115" # Map The current port
    networks:
      - webfluxblog-network-overlay
    volumes:
      - webfluxblog-authentication-server-service-local-volume:/uploads
    environment:
      spring.profiles.active: local-docker


networks:
  webfluxblog-network-overlay:
    external: true

volumes:
  webfluxblog-authentication-server-service-local-volume:
    name: webfluxblog-authentication-server-service-local-volume

# To build, docker-compose up --build -d or generally ./gradlew bootJar && docker-compose up --build -d