debug: true

server:
  port: 8114
  error:
    include-message: always
    include-exception: true
    include-binding-errors: always
    include-stacktrace: always
  shutdown: graceful

spring:
  application:
    name: authentication-server-service
  threads:
    virtual:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  datasource:
    url: jdbc:postgresql://preprod-webfluxblog-mysqlserver:5432/web__authentication_server
    username: postgres
    password: postgres
  sql:
    init:
      mode: always
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true

  data:
    web:
      pageable:
        size-parameter: pageSize
        page-parameter: page
        default-page-size: 20
        one-indexed-parameters: false
        max-page-size: 2000
        prefix: ''
        qualifier-delimiter: _

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://preprod-webfluxblog-authorization-server-service:8111/oauth2/jwks
          issuer-uri: http://preprod-webfluxblog-authorization-server-service:8111



logging:
  level:
    root: INFO
    com.mathias8dev: TRACE
    org.springframework.jdbc: DEBUG
    org.springframework.security: trace
  file:
    name: ./logs/preprod-${spring.application.name}.log


# Eureka client
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://preprod-webfluxblog-eureka-server-service:8084/eureka
  instance:
    hostname: preprod-webfluxblog-eureka-server-service
    prefer-ip-address: true



mesmedocs:
  authentication:
    registered-client-credentials: authorization-server-username:authorization-server-username-password
  gateway:
    baseurl: http://preprod-webfluxblog-gateway-service:8081
    api-url: http://preprod-webfluxblog-gateway-service:8081/api



